### Login API
GET http://localhost:8080/host/login?host=hongman HTTP/1.1

### Login API
POST http://localhost:8080/host/login HTTP/1.1
content-type: application/json

{
    "host" : "hongman"
}

### Logout API
GET http://localhost:8080/host/logout?host=hongman HTTP/1.1


### Logout API
POST http://localhost:8080/host/logout HTTP/1.1
content-type: application/json
authorization: c3d24945-e195-4acc-96eb-5af67508c7b6

{
    "host" : "hongman"
}


### putAllData API
POST http://localhost:8080/host/putAllData HTTP/1.1
content-type: application/json
authorization: c3d24945-e195-4acc-96eb-5af67508c7b6

{
  "datas": [
    {
      "device": "DEVICE1",
      "CommStatus": false,
      "Voltage": 180,
      "ConsumptionCurrent": 20,
      "LeakageCurrent": 1.0,
      "Temperature": 13,
      "Humidity": 10,
      "Alarm": 1,
      "Relay": [true, true, false, false, false]
    },
    {
      "device": "DEVICE2",
      "CommStatus": false,
      "Voltage": 0,
      "ConsumptionCurrent": 0,
      "LeakageCurrent": 0.0,
      "Temperature": 0,
      "Humidity": 0,
      "Alarm": 0,
      "Relay": [true, false, false, false, false]
    },
    {
      "device": "DEVICE3",
      "CommStatus": false,
      "Voltage": 0,
      "ConsumptionCurrent": 0,
      "LeakageCurrent": 0.0,
      "Temperature": 0,
      "Humidity": 0,
      "Alarm": 0,
      "Relay": [true, false, false, false, false]
    },
    {
      "device": "DEVICE4",
      "CommStatus": false,
      "Voltage": 0,
      "ConsumptionCurrent": 0,
      "LeakageCurrent": 0.0,
      "Temperature": 0,
      "Humidity": 0,
      "Alarm": 0,
      "Relay": [true, false, false, false, false]
    },
    {
      "device": "DEVICE5",
      "CommStatus": false,
      "Voltage": 0,
      "ConsumptionCurrent": 0,
      "LeakageCurrent": 0.0,
      "Temperature": 0,
      "Humidity": 0,
      "Alarm": 0,
      "Relay": [false, false, false, false, false]
    }
  ]
}
